# Site settings
title: "Lee Pikeâ€™s Blog"
description: "Things that amuse me."
# baseurl: "/blog"
url: "https://leepike.github.io"

# Build settings
markdown: kramdown
kramdown:
  math_engine: mathjax

theme: minima

# Permalink format for posts
permalink: /blog/:year/:month/:day/:title/

# Exclude temp files
exclude:
  - Gemfile
  - Gemfile.lock
